### ISSUE TITLE
No network drivers for BCM4331 / Macbook Pro 20212

### ISSUE THREAD

**Issue by kimsvane** [ibnsultan/LiteLink-OS#1]
Hi i need to add networking drivers for my BCM43, but i need sudo access to do so, but where do i find the sudo password ?

**Comment by ibnsultan** [comment]
sign out from the kiosk user and sign in with another user:password - `camara:camara`, that will provide you with admin access

**Comment by ibnsultan** [comment]
@kimsvane were u able to install the network drivers

**Comment by kimsvane** [comment]
> @kimsvane were u able to install the network drivers

Yes, i decided to reset root. And got in and had it installed. Works perfectly.
